# Generated by Django 3.0.3 on 2020-07-21 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BosCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='QuosCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='bosrule',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='quosrule',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='bosrule',
            name='bos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.BosCategory'),
        ),
        migrations.AlterField(
            model_name='quosrule',
            name='quos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.QuosCategory'),
        ),
        migrations.DeleteModel(
            name='Bos',
        ),
        migrations.DeleteModel(
            name='Quos',
        ),
    ]
