# Generated by Django 3.0.3 on 2020-07-28 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0002_auto_20200721_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('B', 'BOS'), ('Q', 'QUOS')], default='B', max_length=1)),
                ('name', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_contributions', models.IntegerField(default=20)),
                ('max_selections', models.IntegerField(default=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='bosrule',
            name='bos',
        ),
        migrations.RemoveField(
            model_name='quosrule',
            name='quos',
        ),
        migrations.DeleteModel(
            name='BosCategory',
        ),
        migrations.DeleteModel(
            name='BosRule',
        ),
        migrations.DeleteModel(
            name='QuosCategory',
        ),
        migrations.DeleteModel(
            name='QuosRule',
        ),
        migrations.AddField(
            model_name='contribution',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.Employee'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='factory.Location'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.Rule'),
        ),
    ]
