# Generated by Django 3.0.3 on 2020-07-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0003_auto_20200728_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='order',
            field=models.IntegerField(default=-1),
        ),
    ]
