# Generated by Django 3.0.3 on 2020-07-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0004_rule_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='employee',
            name='surname',
            field=models.CharField(default='', max_length=64),
        ),
    ]
