# Generated by Django 3.0.3 on 2020-07-31 17:43

import adminsortable.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0005_auto_20200731_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='rule',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name_plural': 'Settings'},
        ),
        migrations.AlterField(
            model_name='rule',
            name='category',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.Category'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='order',
            field=models.IntegerField(db_index=True, default=-1, editable=False),
        ),
    ]
