# Generated by Django 3.0.8 on 2020-08-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0006_auto_20200731_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[(1, 'Yellow'), (2, 'Red'), (3, 'Orange'), (4, 'Green'), (5, 'Blue'), (6, 'Gray'), (7, 'Brown')], default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='rule',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[(1, 'BOS'), (2, 'QUOS')], default=1, max_length=1),
        ),
    ]
