# Generated by Django 3.0.8 on 2020-08-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0007_auto_20200801_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('Yellow', 'Yellow'), ('Red', 'Red'), ('Orange', 'Orange'), ('Green', 'Green'), ('Blue', 'Blue'), ('Gray', 'Gray'), ('Brown', 'Brown')], default=1, max_length=8),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('B', 'BOS'), ('Q', 'QUOS')], default=1, max_length=1),
        ),
    ]
