# Generated by Django 3.0.8 on 2020-08-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0009_auto_20200801_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('B', 'BOS'), ('Q', 'QUOS')], default='B', max_length=1),
        ),
    ]
