# Generated by Django 3.0.8 on 2020-08-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0011_auto_20200801_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
