# Generated by Django 3.0.8 on 2020-08-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0013_auto_20200806_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='start_date',
            field=models.DateField(),
        ),
    ]
