# Generated by Django 3.0.8 on 2020-08-11 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0014_auto_20200806_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='rule',
        ),
        migrations.CreateModel(
            name='ContributionRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('P', 'Positive'), ('C', 'Constructive')], default='P', max_length=1)),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.Contribution')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.Rule')),
            ],
        ),
    ]
