# Generated by Django 3.0.8 on 2020-08-14 17:46

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0015_auto_20200811_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='important_rule_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
    ]
