# Generated by Django 3.0.8 on 2020-08-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0016_category_important_rule_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='rule',
            name='name',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
